# Generated by Django 5.1.3 on 2024-12-19 16:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("mainapp", "0002_feedback"),
    ]

    operations = [
        migrations.CreateModel(
            name="Seller",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                ("name", models.CharField(max_length=40, verbose_name="seller")),
                (
                    "iin",
                    models.CharField(
                        blank=True,
                        max_length=12,
                        null=True,
                        verbose_name="individual identification number",
                    ),
                ),
                ("country", models.CharField(blank=True, max_length=40, null=True)),
            ],
            options={
                "db_table": "seller",
            },
        ),
    ]
