# Generated by Django 5.1.3 on 2024-12-19 16:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("mainapp", "0003_seller"),
    ]

    operations = [
        migrations.AddField(
            model_name="seller",
            name="product",
            field=models.ManyToManyField(to="mainapp.product"),
        ),
    ]
