# Generated by Django 5.1.3 on 2024-12-19 16:42

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("mainapp", "0004_seller_product"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="seller",
            name="product",
        ),
    ]
