# Generated by Django 5.1.3 on 2024-12-19 16:53

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("mainapp", "0006_product_seller"),
    ]

    operations = [
        migrations.AlterField(
            model_name="product",
            name="seller",
            field=models.ForeignKey(
                default=1,
                on_delete=django.db.models.deletion.CASCADE,
                to="mainapp.seller",
                verbose_name="seller",
            ),
        ),
    ]
