# Generated by Django 5.1.3 on 2024-12-26 16:15

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("mainapp", "0007_alter_product_seller"),
    ]

    operations = [
        migrations.AddField(
            model_name="product",
            name="sales_count",
            field=models.PositiveIntegerField(default=0),
        ),
        migrations.AlterField(
            model_name="feedback",
            name="product",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="feedback",
                to="mainapp.product",
            ),
        ),
    ]
