# Generated by Django 5.1.3 on 2024-12-28 14:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("mainapp", "0009_deliverymethod_deliveryinformation_delivery_method"),
    ]

    operations = [
        migrations.CreateModel(
            name="Tags",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                ("name", models.CharField(max_length=30, verbose_name="Tag")),
                ("deleted", models.BooleanField(default=False)),
                ("product", models.ManyToManyField(to="mainapp.product")),
            ],
            options={
                "verbose_name": "Tag",
                "verbose_name_plural": "Tags",
                "db_table": "Tags",
            },
        ),
    ]
