# Generated by Django 5.1.3 on 2025-01-05 12:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("mainapp", "0010_tags"),
    ]

    operations = [
        migrations.AddField(
            model_name="product",
            name="weight",
            field=models.DecimalField(decimal_places=3, default=1, max_digits=5),
        ),
    ]
