# Generated by Django 5.1.3 on 2025-01-09 16:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("mainapp", "0011_product_weight"),
    ]

    operations = [
        migrations.AddField(
            model_name="seller",
            name="rating",
            field=models.DecimalField(
                decimal_places=2, default=0, max_digits=3, verbose_name="Rating"
            ),
        ),
    ]
