# Generated by Django 5.1.3 on 2025-01-22 16:07

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("mainapp", "0013_productqueue"),
    ]

    operations = [
        migrations.RenameField(
            model_name="productqueue",
            old_name="product_id",
            new_name="product",
        ),
    ]
