# Generated by Django 5.1.3 on 2025-02-21 16:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("mainapp", "0014_rename_product_id_productqueue_product"),
    ]

    operations = [
        migrations.AddField(
            model_name="product",
            name="image",
            field=models.ImageField(
                blank=True, null=True, upload_to="products", verbose_name="Pictures"
            ),
        ),
    ]
